### ISSUE TITLE
bk on NetBSD

### ISSUE THREAD

**Issue by voidpin** [aeosynth/bk#10]
FYI, I've packaged `bk` for NetBSD.
Due to the on-going package freeze ahead of the Q4-release, the package is currently in the WIP-repo, https://mail-index.netbsd.org/pkgsrc-wip-changes/2020/12/22/msg018889.html

Once the freeze is over, I'll import the package into the main branch.

**Comment by aeosynth** [comment]
Cool, do you need me to do anything? I don't think this needs to be an issue, maybe better in the new discussions tab.

**Comment by voidpin** [comment]
No, the package builds and works fine. Just thought, you'd like to know it. Feel free to close this issue.

**Comment by voidpin** [comment]
@aeosynth `bk` has now been imported into the main branch.
