### ISSUE TITLE
Strange double underline which dissapears after scroll

### ISSUE THREAD

**Issue by rofrol** [aeosynth/bk#15]
![image](https://user-images.githubusercontent.com/28787/103499397-304e9400-4e48-11eb-87e1-ca5aa75b61f6.png)

And here after scroll:

![image](https://user-images.githubusercontent.com/28787/103499409-3fcddd00-4e48-11eb-8279-17dba27d7ad3.png)

**Comment by aeosynth** [comment]
dupe of #9 . which terminal does this happen in?

**Comment by rofrol** [comment]
gnome-terminal Ubuntu 20.10
