### ISSUE TITLE
[question] will there be a new public release?

### ISSUE THREAD

**Issue by paoloschi** [aeosynth/bk#22]
Compiling from source is really smoothly but an updated release would help me in requesting the Void Linux -the O.S. I use- maintainers to have _bk_ added as an official package in the distribution repository. 
I want to do this because _bk_ is the best terminal epub reader I've tried to date :-)
Thank you for this really well thought out project!

**Comment by aeosynth** [comment]
i'll try

**Comment by j0hnd3v** [comment]
This is important. Many distributions have a policy of only keeping software with recent changes and popularity in the repository. Unmaintained software is eventually excluded because it becomes the target of a vulnerability. It would be interesting to have some change even if cosmetic.

**Comment by aeosynth** [comment]
i'll try again

**Comment by aeosynth** [comment]
i want to rewrite this but one step holding me back is the merging of states to get the final rendered text formatting, which is overly complicated currently

**Comment by aeosynth** [comment]
to make this actionable, i'm looking for resources on text rendering. doesn't necessarily have to be rust or terminals, but more on how to deal with overlapping layers of formatting at book scale (~100k-1M words).

**Comment by aeosynth** [comment]
a new version has been published, and some new developments are planned
