### ISSUE TITLE
Request: be more permissive with poorly formatted epub

### ISSUE THREAD

**Issue by kevinclevenger** [aeosynth/bk#26]
In books converted from .lit with clit I get:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bk-0.5.3/src/epub.rs:139:41
epr says AttributeError: 'Epub' object has no attribute 'toc'

Also as in issue #13 / #25, not sure anything can be done outside of roxmltree though 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownEntityReference("lsquo", TextPos { row: 11, col: 35 })', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bk-0.5.3/src/epub.rs:57:63

Both of the above are readable with Moon+ Reader on Android. It would be nice if bk could be a little more permissive.

**Comment by aeosynth** [comment]
i'm willing to accept a pr that changes the xml library to a more permissive one

if clit generates bad epub xml then you should report that bug to them

closing as dup of #13
