### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kenderipa** [aeosynth/bk#29]
Hello,

thanks for the great console reader. Could you please make a release after all the changes taken since 2021? 

Also, is this project abandoned? If yes, it would be great shame and pity, since it's the only console reader I'm aware of, which is not written in python. And python is, you know, slow and greedy.

**Comment by hollisticated-horse** [comment]
I'd also love to see this ebook reader at least arrive at feature parity with epy.

**Comment by aeosynth** [comment]
It's not exactly abandoned but I use Foliate nowadays for reading, and my code is brittle and needs a different approach.

This might come off as begging, but if anyone would sponsor the project (through ko-fi or other) I'd be more willing to come back to this. Otherwise it's in limbo of maybe one day.

**Comment by kenderipa** [comment]
Well, I could donate you a couple of coffees. I'm not sure if it would be enough, but it will be more that I've ever donated for a free software piece. Before that, however, I wanted to ask a couple of questions. First, will it actually be enough for further development? Second, what do you mean by different approach? Complete rewrite? Right now bk is very light weight, and I would be immensely happy if it will stay exactly as it is in this in this facet. 

Also, I've tried goreader and book from your links above. Goreader compiles and is about as lightweight as bk, is, however, a bit barebones. book, however, is the heaviest book reader I ever tried, about 400 megs of RAM. Even heavier than baca. tbr didn't compile for me.

**Comment by aeosynth** [comment]
that would be enough for an immediate new release, plus a later rewrite. the rewrite would use a new tui library [ratatui](https://ratatui.rs/), but should stay lightweight.

**Comment by kenderipa** [comment]
All right, done.

**Comment by aeosynth** [comment]
cool i'll get started

**Comment by hollisticated-horse** [comment]
I've also bought you a nice KoFi :D I'll look at the alternatives you mentioned. 
I don't think I would consider your request begging. I respect the fact that you value your time. 
Makes me wonder how such a request would work an no-currency economy. What could we have traded in exchange for your time working on bk.

**Comment by aeosynth** [comment]
ok, published the new version. no estimate when the next version will come out, but it will come out
