### ISSUE TITLE
clicking links

### ISSUE THREAD

**Issue by aeosynth** [aeosynth/bk#3]
we should explore ways to make links easier to click, those single character footnotes are annoying.

- make the hitbox larger by a fixed amount (1 col/row padding)

- partition the screen into hitboxes, visually selecting a link on mouse move. example: tiling window manager.

keyboard selection seems solved, a key to highlight and label all links, type the label to follow

**Comment by Seirdy** [comment]
Might be worth looking into using OSC 8 escape sequences. [Some programs] already do this.

**Comment by aeosynth** [comment]
That's cool, thanks for the link. I'll wait until alacritty supports that feature, or until I switch to a terminal which does, but PR welcome.

**Comment by aeosynth** [comment]
i think the 'correct' solution is to use the unicode link emoji (🔗), but that depends on both terminal emoji support, and an emoji font installed, which seems like too small a fraction of users to bother with. may revisit this in the future.

really the best solution would be to implement keyboard link selection.
