### ISSUE TITLE
Release it as a binary on github

### ISSUE THREAD

**Issue by m040601** [aeosynth/bk#6]
Thank you for your work. Eager to try this to compare to epr.
Would it be possible to release it as a binary ? At least compiled for x86_64.
It would make it much easier to release this as a precompiled package (as an alternative to a source package) for arch linux and other distros. It would make much easier for people who dont have / dont want to download the 500 mega rust distribution just to quickly try it out.

Also, think of low spec devices like less powered old laptops or the Rasbperry Pi, where constantly recompiling compiling may not be that desirable

**Comment by aeosynth** [comment]
i would like to automatically create release binaries with github actions. PR welcome.

**Comment by aeosynth** [comment]
alright i manually added a release
