### ISSUE TITLE
Move cursor with table of contents

### ISSUE THREAD

**Issue by tspivey** [aeosynth/bk#8]
If you activate the table of contents with tab, the hardware cursor isn't put on the selected item.
This makes it impossible to find your location if using a screen reader or braille display.
The cursor should be able to be moved even while still hidden.

**Comment by aeosynth** [comment]
will fix, thanks for reporting

**Comment by aeosynth** [comment]
@tspivey hi, could you check master to see if this is fixed? idk how to test on my own.

**Comment by tspivey** [comment]
It works well here, except the cursor isn't moved back to the top after leaving the table of contents.

**Comment by aeosynth** [comment]
When rendering a page of text, the cursor is left at the bottom, is that an issue, or does the screen reader automatically wrap around?
