### ISSUE TITLE
bold reset = double underline

### ISSUE THREAD

**Issue by aeosynth** [aeosynth/bk#9]
apparently `nobold` is inconsistent, sometimes treated as `double underline`. will have to go back to using `reset` everywhere, or maybe `normalintensity`

affects at least: kitty, gnome-terminal, xterm, termite, xfce4-terminal

**Comment by fraserli** [comment]
Also reproducible using xterm, termite, or xfce4-terminal.

**Comment by aeosynth** [comment]
fixed w/ https://github.com/aeosynth/bk/commit/48786a80c2f96afd9a935688015ffd5da1cbfeb0
